FORMAT: 1A

# Decorist APIs

These are decorist APIs

## Group products

Products API for all brands, selection of brand-specific data sets is done using the "sitecode" attribute

### /products

#### GET

+ Response 200 (application/json)

    Properties (Decorist, One Kings Lane, etc)

    + Body

            [
                {
                    "UUID": "[Product UUID]",
                    "name": "Product name",
                    "category": [
                        {
                            "UUID": "Category UUID",
                            "name": "Category Name"
                        },
                        
                    ],
                    "CreationDate": "Date",
                    "price": "Product price"
                },
                
            ]

#### POST

+ Response 201 (application/json)

    OK

    + Body

            {
              "UUID": "New product UUID"
            }

### /products/search

#### 

### /products/{pk}

#### GET

+ Parameters

    + pk (required)

+ Response 200 (application/json)

    OK

    + Body

            {
                "UUID": "[Product UUID]",
                "name": "Product name",
                "category": [
                    {
                        "UUID": "Category UUID",
                        "name": "Category Name"
                    },
                    
                ],
                "color": [
                    {
                        "UUID": "Color UUID",
                        "name": "Color Name"
                    },
                    
                ],
                "vendor":{
                            "UUID": "Vendor UUID",
                            "name": "Vendor Name"
                        },
                "vendor_url": "Vendor site URL",
                "images": [
                    "image url",
                    
                ],
                "size": {
                    "unit": "inches",
                    "height": "10",
                    "width": "10",
                    "depth": "10"
                },
                "style": [
                    "style ID",
                    
                ],
                "meta": {
                    "Keywords": "Product keywords",
                    "Description": "Product Description",
                    "canonical": "Product canonical URL"
                },
                "price": "15.21",
                "item_availability": Boolean,
                "CreationDate": "Date"
            },

#### PUT

+ Parameters

    + pk (required)

+ Response 204 (application/json)

#### DELETE

+ Parameters

    + pk (required)

+ Response 204 (application/json)

## Group design-solutions

APIs for design-solution

### /design-solutions

#### GET

+ Response 200 (application/json)

    OK

    + Body

            {
                [
                    {
                        "UUID": "[Solution UUID]",
                        "Key": "Solution Key",
                        "Designer": {
                            "UUID": "Designer UUID"
                        },
                        "Customer": {
                            "UUID": "Customer UUID"
                        },
                        "Room": "Solution room",
                        "CreationDate": "Date",
                        "InternalDueDate": "Date",
                        "ExternalDueDate": "Date",
                        "Status": "Solution Status",
                        "Notes": "Solution Notes"
                    },
                    
                ]
            }

#### POST

+ Response 201 (application/json)

    OK

    + Body

            {
              "UUID": "New solution UUID"
            }

### /design-solutions/list_by_designer

#### 

### /design-solutions/list_by_user

#### 

### /design-solutions/search

#### 

### /design-solutions/{pk}

#### GET

+ Parameters

    + pk (required)

+ Response 200 (application/json)

    OK

    + Body

            {
              "UUID": "[Solution UUID]",
              "Key": "Solution Key",
              "Designer": {
                "UUID": "Designer UUID"
              },
              "Customer": {
                "UUID": "Customer UUID"
              },
              "Room": "Solution room",
              "CreationDate": "Date",
              "InternalDueDate": "Date",
              "ExternalDueDate": "Date",
              "Status": "Solution Status",
              "Notes": "Solution Notes"
            }

#### PUT

+ Parameters

    + pk (required)

+ Response 204 (application/json)

#### DELETE

+ Parameters

    + pk (required)

+ Response 204 (application/json)

## Group boards

Operations about design boards

### /boards

#### GET

+ Response 200 (application/json)

    OK

    + Body

            {
                [
                    {
                        "UUID": "[Board UUID]",
                        "Author": {
                            "UUID": "Author UUID"
                        },
                        "CreationDate": "Date",
                        "Name": "Board Name"
                    },
                    
                ]
            }

#### POST

+ Response 201 (application/json)

    OK

    + Body

            {}

### /boards/list_by_author

#### 

### /boards/search

#### 

### /boards/{pk}

#### GET

+ Parameters

    + pk (required)

+ Response 200 (application/json)

    Primary key

    + Body

            {
              "UUID": "New Board UUID"
            }

#### PUT

+ Parameters

    + pk (required)

+ Response 204 (application/json)

#### DELETE

+ Parameters

    + pk (required)

+ Response 204 (application/json)

### /boards/{pk}/send

#### POST

+ Parameters

    + pk (required)

+ Response 204 (application/json)

## Group user

Operations about user

### /users

#### GET

+ Response 200 (application/json)

    OK

    + Body

            {
                [
                    {
                        "UUID": "[User UUID]",
                        "first_name": "First Name", 
                        "last_name": "Last Name",
                        "is_admin": Boolean,
                        "groups": [
                            {
                                "UUID": "Group UUID",
                                "Name": "Group name"
                            },
                            
                        ],
                        "CreationDate": "Date"
                    },
                    
                ]
            }

#### POST

+ Response 201 (application/json)

    OK

    + Body

            {
              "UUID": "New User UUID"
            }

### /users/list_by_group

#### 

### /users/search

#### 

### /users/{pk}

#### GET

+ Parameters

    + pk (required)

+ Response 200 (application/json)

    Primary key

    + Body

            {
                "UUID": "[User UUID]",
                "first_name": "First Name", 
                "last_name": "Last Name",
                "is_admin": Boolean,
                "groups": [
                    {
                        "UUID": "Group UUID",
                        "Name": "Group name"
                    },
                    
                ],
                "CreationDate": "Date"
            }

#### PUT

+ Parameters

    + pk (required)

+ Response 204 (application/json)

#### DELETE

+ Parameters

    + pk (required)

+ Response 204 (application/json)

### /users/reset_password

#### POST

+ Response 204 (application/json)

## Group design-orders

Operations about design-orders

### /design-orders

#### GET

+ Response 200 (application/json)

    OK

    + Body

            {
                [
                    {
                        "UUID": "[User UUID]",
                        "first_name": "First Name", 
                        "last_name": "Last Name",
                        "is_admin": Boolean,
                        "groups": [
                            {
                                "UUID": "Group UUID",
                                "Name": "Group name"
                            },
                            
                        ],
                        "CreationDate": "Date"
                    },
                    
                ]
            }

#### POST

+ Response 201 (application/json)

    OK

    + Body

            {
              "UUID": "New User UUID"
            }

### /design-orders/search

#### 

### /design-orders/{pk}

#### GET

+ Parameters

    + pk (required)

+ Response 200 (application/json)

    Primary key

    + Body

            {
                "UUID": "[User UUID]",
                "first_name": "First Name", 
                "last_name": "Last Name",
                "is_admin": Boolean,
                "groups": [
                    {
                        "UUID": "Group UUID",
                        "Name": "Group name"
                    },
                    
                ],
                "CreationDate": "Date"
            }

#### DELETE

+ Parameters

    + pk (required)

+ Response 204 (application/json)
